### PR TITLE
Implicit group by

### LINKED ISSUE #347: COUNT failing when GROUP BY absent
Currently: COUNT and other aggregations do not workin the absence of GROUP BY and COUNT(*)

Expected result: COUNT and other aggregations should work in the absence of GROUP BY and should also work with COUNT(*).

The following query fails with the infamous "java.util.NoSuchElementException: Either.right.value on Left"

```
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dm:     <http://gsk-kg.rdip.gsk.com/dm/1.0/>
PREFIX semmed: <http://gsk-kg.rdip.gsk.com/semmed/>
PREFIX umls:   <http://gsk-kg.rdip.gsk.com/umls/>
SELECT (COUNT(?s) as ?count)
FROM <http://id.gsk.com/dataset/elsevier/>
WHERE
{
	?s a dm:LinkedEntity .
}
```

The following query also fails:
```
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dm:     <http://gsk-kg.rdip.gsk.com/dm/1.0/>
PREFIX semmed: <http://gsk-kg.rdip.gsk.com/semmed/>
PREFIX umls:   <http://gsk-kg.rdip.gsk.com/umls/>
SELECT (COUNT(*) as ?count)
FROM <http://id.gsk.com/dataset/elsevier/>
WHERE
{
	?s a dm:LinkedEntity .
}
```
The following query also does not work:
```
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dm:     <http://gsk-kg.rdip.gsk.com/dm/1.0/>
PREFIX semmed: <http://gsk-kg.rdip.gsk.com/semmed/>
PREFIX umls:   <http://gsk-kg.rdip.gsk.com/umls/>
SELECT (COUNT(*) as ?count)
FROM <http://id.gsk.com/dataset/elsevier/>
WHERE
{
	?s a dm:LinkedEntity .
} GROUP BY ?s
```

It seems like COUNT will only work with GROUPBY and COUNT(?s). The following query works:

```
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dm:     <http://gsk-kg.rdip.gsk.com/dm/1.0/>
PREFIX semmed: <http://gsk-kg.rdip.gsk.com/semmed/>
PREFIX umls:   <http://gsk-kg.rdip.gsk.com/umls/>
SELECT (COUNT(?s) as ?count)
FROM <http://id.gsk.com/dataset/elsevier/>
WHERE
{
	?s a dm:LinkedEntity .
} GROUP BY ?s
```

### PR DESCRIPTION
**Pull request by pepegar**
We were parsing always expecting at least a variable to group by for.  Now we also accept implicit groupby.

Closes #347

### CODE REVIEW

File: modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala [hunk 1]
```diff
@@ -78,7 +78,7 @@ object ExprParser {
 
   def groupParen[_: P]: P[Group] = P(
     "(" ~ group ~ "(" ~ (StringValParser.variable).rep(
-      1
+      0
```
Comment (patofp) [inline modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala:81]: 👍

**Review by patofp — APPROVED** [review]
LGTM!
